clear;
m=1200; n=200;
A = rand(m, n);
B=A;
b= rand(m,1);
%[Q, R] = qr(A);
[Q1, R1] = thinqr(A);
x = linsolve(R1, Q1' *b);
[Q_t, R_t] = qr(B, "econ");
x_t= A\b;
disp(norm(x-x_t));
disp(norm(A*x - b));
disp(norm(A*x_t - b));
%syms a b c d e f g h i j k l m;
%Q = [[1 0 0 0];[0 1 0 0];[0 0 a b];[0 0 c d]];
%H = [[1 0 0 0];[0 e f g];[0 h i j];[ 0 k l m]];
%[Qm, Rm] = myqr(A);
%fprintf("Q error: %e, R error: %e", sum(abs(Q-Qm), 'all'), sum(abs(R-Rm),'all'));